### ISSUE TITLE
Issue with README module imports

### ISSUE THREAD

**Issue by derekclee** [pubnub/graphql-pubnub-subscriptions#2]
The README indicates:

```
import { PNPubSub } from '@pubnub/graphql-pubnub-subscriptions';
```

What worked for me was:

```
import { PNPubSub } from "graphql-pubnub-subscriptions";
```

Was the intent to publish the package under `@pubnub`?

Thanks for this package.

**Comment by polarweasel** [comment]
#4 fixes this one. Thanks for the report @derekclee!
